### ISSUE TITLE
Cannot assign to read only property 'readyState' of object '#<WebSocket>

### ISSUE THREAD

**Issue by yidongw** [romgain/jest-websocket-mock#53]
I was following the example but it gives me the following error. Can you please help?

```
  console.error
    Error: Uncaught [TypeError: Cannot assign to read only property 'readyState' of object '#<WebSocket>']
        at reportException (/Users/alanwang/*/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at Timeout.task [as _onTimeout] (/Users/alanwang/*/node_modules/jsdom/lib/jsdom/browser/Window.js:396:9)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7) TypeError: Cannot assign to read only property 'readyState' of object '#<WebSocket>'
        at WebSocket.delayCallback (/Users/alanwang/*/node_modules/mock-socket/src/websocket.js:81:26)
        at /Users/alanwang/*/node_modules/mock-socket/src/helpers/delay.js:10:41
        at Timeout.task [as _onTimeout] (/Users/alanwang*/node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:396:9)
```

**Comment by romgain** [comment]
Hi @yidongw 

can you please share a small reproducer?

**Comment by yidongw** [comment]
Sorry it is caused by my misuse of mobx. Jest-websocket-mock is good. closing this issue
